language: go
go:
- 1.10.x
script: make test
notifications:
  slack:
    secure: d4PxCAfQ8FM9GbNrgcWvvxYqcL3y5GqPRrcOhLM1na7EKgC3hcJPTO4lDyN/CtDQRZXjumjw7TWetY3kk/PSZN58ETZmtjHIKFYCoDZiadYj14WYD7s2K+WP7Q17ASTXpEOl+k/5zDE91aGW2lup5Eqzc/YOBjVhydxU1Wp3t+o7BXzyQtsRtSLPNm17uIrR3IGLydIhF3AGoEgTG+on72/2zMHc/zP9zKY1wxfIt06Q+MjXm9rOIo8vcW7pHJkU6VZbRD+TPtACqrdASO03znGBAESdrp0BtasJehOp9U3HyvPm5v4Da5/0MHcFs8TsRkoJoZ5KWNGNkxflm6rA++CUtIP8H7PB5k83atnL9ZRlOWgWaEYYJGANR18hRmKSDbYxmc6XOy00Q5N+qTNmuzILlH2z0B0PpMkBRYSWrKeVxbzK1iYrUY5AX2NSzMPsBmlaVdOzFnikLFHtoVeYEM4ca6ATuYk0fD0PpKWrVl9hMkERgUiFy2UDaoQChYfiKBsE8e+vk6aZ+8pLPzzK1CvM8lHr7wGMcMqEAb/S/XBXdWxMEGxwx3lk4BWVJon5n4CdvrfBjMfkGNzON4pRZRmGkX0Q27KLUIrWqK8jpBUwKnQA8IOW7qZiDSKv3ZxnXi2icK7ltnI9e3obKIvWx7LY7qLQ9kWZydwzwmFgtmM=
